version: '3.8'

services:
  app-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: task-management-test
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=test
      - PORT=3000
      - JWT_SECRET=test_secret_key
      - JWT_EXPIRES_IN=1d
    networks:
      - test-network

networks:
  test-network:
    driver: bridge